name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/178208925536/locations/global/workloadIdentityPools/github
        service_account: principalSet://iam.googleapis.com/projects/178208925536/locations/global/workloadIdentityPools/github/attribute.repository/pitt-cs-1660

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile  # Path to your Dockerfile
        push: true
        tags: us-east5-docker.pkg.dev/build-push-project/my-repository/node-demo:v1  # Adjust your image name/tag accordingly

