name: CI

on:
  push:
    branches:
      - main
      - login-gcr.io

permissions:
  contents: 'read'     # For accessing repository contents
  id-token: 'write'    # For Workload Identity Federation

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Authenticate to GCP using Workload Identity Federation
      - uses: google-github-actions/auth@v2
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'iam-permissions-440300' # your project ID
          workload_identity_provider: 'projects/588915074981/locations/global/workloadIdentityPools/github/providers/my-repo' # update with your provider

      # Step 3: Configure Docker to use GCP's Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east5-docker.pkg.dev

      # Step 4: Set up Docker Buildx for multi-platform builds
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # Step 5: Build and push the Docker image to Artifact Registry
      - name: Build and Push Docker Image to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-east5-docker.pkg.dev/iam-permissions-440300/build-push/node-demo:v1 # update with your image details